<?php
return
    [
        [
            'menu_name' => '首页',
            'menu_key' => 'overview',
            'menu_type' => 1,
            'icon' => 'element-Monitor',
            'api_url' => '',
            'router_path' => 'index',
            'view_path' => 'index/index',
            'methods' => '',
            'sort' => 100,
            'status' => 1,
            'is_show' => 0
        ],
        [
            'menu_name' => '应用管理',
            'menu_key' => 'app_manage',
            'menu_type' => 0,
            'icon' => 'element-Monitor',
            'api_url' => '',
            'router_path' => 'app_manage',
            'view_path' => '',
            'methods' => '',
            'sort' => 99,
            'status' => 1,
            'is_show' => 0,
            'children' => [
                [
                    'menu_name' => '工具管理',
                    'menu_key' => 'app_manage_tool',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconchajian1',
                    'api_url' => '',
                    'router_path' => 'tools',
                    'view_path' => 'index/tools',
                    'methods' => 'get',
                    'sort' => 30,
                    'status' => 1,
                    'is_show' => 1
                ],
                [
                    'menu_name' => '应用管理',
                    'menu_key' => 'app_manage_index',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => '',
                    'router_path' => 'index',
                    'view_path' => 'index/app_manage',
                    'methods' => 'get',
                    'sort' => 10,
                    'status' => 1,
                    'is_show' => 1
                ],
                [
                    'menu_name' => '插件管理',
                    'menu_key' => 'app_manage_store',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => '',
                    'router_path' => 'app_store',
                    'view_path' => 'index/store',
                    'methods' => 'get',
                    'sort' => 10,
                    'status' => 1,
                    'is_show' => 1
                ]
            ]
        ],
        [
            'menu_name' => '站点管理',
            'menu_key' => 'site_manage',
            'menu_type' => 0,
            'icon' => 'element-Memo',
            'api_url' => '',
            'router_path' => 'site',
            'view_path' => '',
            'methods' => '',
            'sort' => 50,
            'status' => 1,
            'is_show' => 0,
            'children' => [
                [
                    'menu_name' => '站点列表',
                    'menu_key' => 'site_list',
                    'menu_type' => 1,
                    'icon' => 'element-OfficeBuilding',
                    'api_url' => 'site/site',
                    'router_path' => 'list',
                    'view_path' => 'site/list',
                    'methods' => 'get',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '添加站点',
                            'menu_key' => 'add_site',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'site/site',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'post',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '编辑站点',
                            'menu_key' => 'edit_site',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'site/site/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'put',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '删除站点',
                            'menu_key' => 'delete_site',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'site/site/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'delete',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '站点用户',
                    'menu_key' => 'site_user_list',
                    'menu_type' => 1,
                    'icon' => 'element-OfficeBuilding',
                    'api_url' => 'site/user',
                    'router_path' => 'user',
                    'view_path' => 'site/user',
                    'methods' => 'get',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '用户详情',
                    'menu_key' => 'site_user_info',
                    'menu_type' => 1,
                    'icon' => 'element-OfficeBuilding',
                    'api_url' => '',
                    'router_path' => 'user_info',
                    'view_path' => 'site/user_info',
                    'methods' => 'get',
                    'sort' => 99,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '站点详情',
                    'menu_key' => 'site_info',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => 'site/site/<site_id>',
                    'router_path' => 'info',
                    'view_path' => 'site/info',
                    'methods' => 'get',
                    'sort' => 90,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '站点套餐',
                    'menu_key' => 'site_group',
                    'menu_type' => 1,
                    'icon' => 'element-PriceTag',
                    'api_url' => 'site/group',
                    'router_path' => 'group',
                    'view_path' => 'site/group',
                    'methods' => 'get',
                    'sort' => 80,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '站点套餐',
                    'menu_key' => 'site_group_edit',
                    'menu_type' => 1,
                    'icon' => 'element-PriceTag',
                    'api_url' => 'site/group_edit',
                    'router_path' => 'group_edit',
                    'view_path' => 'site/group_edit',
                    'methods' => 'get',
                    'sort' => 70,
                    'status' => 1,
                    'is_show' => 0,
                ]
            ]
        ],
        [
            'menu_name' => '系统设置',
            'menu_key' => 'setting_manage',
            'menu_type' => 0,
            'icon' => 'element-Setting',
            'api_url' => '',
            'router_path' => 'setting',
            'view_path' => '',
            'methods' => '',
            'sort' => 20,
            'status' => 1,
            'is_show' => 1,
            'children' => [
                [
                    'menu_name' => '权限设置',
                    'menu_key' => 'auth',
                    'menu_type' => 0,
                    'icon' => 'iconfont-iconquanxianguanli',
                    'api_url' => '',
                    'router_path' => 'auth',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 40,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '管理员',
                            'menu_key' => 'auth_list',
                            'menu_type' => 1,
                            'icon' => 'element-Lock',
                            'api_url' => '',
                            'router_path' => 'user',
                            'view_path' => 'auth/user',
                            'methods' => '',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '管理员角色',
                            'menu_key' => 'auth_role',
                            'menu_type' => 1,
                            'icon' => 'iconfont-iconhuiyuanliebiao',
                            'api_url' => 'sys/role',
                            'router_path' => 'role',
                            'view_path' => 'auth/role',
                            'methods' => 'get',
                            'sort' => 70,
                            'status' => 1,
                            'is_show' => 1,
                            'children' => [
                                [
                                    'menu_name' => '新增',
                                    'menu_key' => 'auth_role_add',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/role',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'post',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '编辑',
                                    'menu_key' => 'auth_role_update',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/role/<role_id>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'put',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '删除',
                                    'menu_key' => 'auth_role_del',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/role/<role_id>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'delete',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                            ]
                        ],
                        [
                            'menu_name' => '操作日志',
                            'menu_key' => 'auth_log',
                            'menu_type' => 1,
                            'icon' => 'element-Document',
                            'api_url' => 'sys/log',
                            'router_path' => 'log',
                            'view_path' => 'auth/log',
                            'methods' => 'get',
                            'sort' => 60,
                            'status' => 1,
                            'is_show' => 1,
                        ]
                    ]
                ],
                [
                    'menu_name' => '网站设置',
                    'menu_key' => 'website_setting',
                    'menu_type' => 0,
                    'icon' => 'iconfont-iconwangzhan1',
                    'api_url' => '',
                    'router_path' => 'website',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 80,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '基础设置',
                            'menu_key' => 'base_setting',
                            'menu_type' => 1,
                            'icon' => 'element-Basketball',
                            'api_url' => 'sys/config/website',
                            'router_path' => 'system',
                            'view_path' => 'setting/system',
                            'methods' => 'get',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '版权设置',
                            'menu_key' => 'setting_copyright',
                            'menu_type' => 1,
                            'icon' => 'iconfont-iconbanquan1',
                            'api_url' => 'sys/config/copyright',
                            'router_path' => 'copyright',
                            'view_path' => 'setting/copyright',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '登录设置',
                    'menu_key' => 'setting_login',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconzhuceshezhi',
                    'api_url' => 'sys/config/login',
                    'router_path' => 'adminlogin',
                    'view_path' => 'setting/adminlogin',
                    'methods' => 'get',
                    'sort' => 20,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '存储设置',
                    'menu_key' => 'setting_storage',
                    'menu_type' => 1,
                    'icon' => 'element-FolderChecked',
                    'api_url' => 'sys/storage',
                    'router_path' => 'storage',
                    'view_path' => 'setting/storage',
                    'methods' => 'get',
                    'sort' => 30,
                    'status' => 1,
                    'is_show' => 1
                ],
                [
                    'menu_name' => '微信开放平台',
                    'menu_key' => 'setting_oplatform',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconweixin',
                    'api_url' => 'sys/wxoplatform',
                    'router_path' => 'oplatform',
                    'view_path' => 'setting/wxoplatform',
                    'methods' => 'get',
                    'sort' => 20,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '小程序平台',
                    'menu_key' => 'setting_weapp_oplatform',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconxiaochengxushezhi',
                    'api_url' => 'sys/weapp',
                    'router_path' => 'weapp',
                    'view_path' => 'setting/weapp',
                    'methods' => 'get',
                    'sort' => 20,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '素材管理',
                    'menu_key' => 'attachment',
                    'menu_type' => 1,
                    'icon' => 'element-Files',
                    'api_url' => 'sys/attachment',
                    'router_path' => 'attachment',
                    'view_path' => 'tools/attachment',
                    'methods' => 'get',
                    'sort' => 10,
                    'status' => 1,
                    'is_show' => 1,
                ]
            ]
        ],
        [
            'menu_name' => '开发工具',
            'menu_key' => 'tool',
            'menu_type' => 0,
            'icon' => 'element-Edit',
            'api_url' => '',
            'router_path' => 'tools',
            'view_path' => '',
            'methods' => '',
            'sort' => 10,
            'status' => 1,
            'is_show' => 0,
            'children' => [
                [
                    'menu_name' => '插件开发',
                    'menu_key' => 'addon_develop',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconchajiankaifa',
                    'api_url' => '',
                    'router_path' => 'addon',
                    'view_path' => 'tools/addon/index',
                    'methods' => '',
                    'sort' => 110,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '插件添加/编辑',
                    'menu_key' => 'addon_edit',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => '',
                    'router_path' => 'addon_edit',
                    'view_path' => 'tools/addon/edit',
                    'methods' => 'get',
                    'sort' => 90,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '数据字典',
                    'menu_key' => 'sys_dict_dict_dict_list',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconwenzhangguanli1',
                    'api_url' => 'dict/post/post',
                    'router_path' => 'list',
                    'view_path' => 'dict/list',
                    'methods' => 'get',
                    'sort' => 90,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '数据字典添加',
                            'menu_key' => 'sys_dict_dict_dict_add',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'dict',
                            'router_path' => 'edit',
                            'view_path' => 'dict/edit',
                            'methods' => 'post',
                            'sort' => 4,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '编辑',
                            'menu_key' => 'sys_dict_dict_dict_edit',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'dict/<id>',
                            'router_path' => 'edit',
                            'view_path' => 'dict/edit',
                            'methods' => 'put',
                            'sort' => 3,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '删除',
                            'menu_key' => 'sys_dict_dict_dict_delete',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'dict/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'delete',
                            'sort' => 2,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '代码生成',
                    'menu_key' => 'code',
                    'menu_type' => 1,
                    'icon' => 'iconfont-icondaimashengcheng',
                    'api_url' => 'generator/generator',
                    'router_path' => 'code',
                    'view_path' => 'tools/code/index',
                    'methods' => 'get',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '数据表编辑',
                    'menu_key' => 'code_edit',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => '',
                    'router_path' => 'code/edit',
                    'view_path' => 'tools/code/edit',
                    'methods' => '',
                    'sort' => 80,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '更新缓存',
                    'menu_key' => 'tools_Update_cache',
                    'menu_type' => 1,
                    'icon' => 'iconfont-icongengxinhuancun',
                    'api_url' => '',
                    'router_path' => 'update',
                    'view_path' => 'tools/updatecache',
                    'methods' => '',
                    'sort' => 60,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '环境检测',
                    'menu_key' => 'tools_check_environment',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconhuanjingjiance',
                    'api_url' => '',
                    'router_path' => 'detection',
                    'view_path' => 'tools/detection',
                    'methods' => '',
                    'sort' => 50,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '系统菜单',
                    'menu_key' => 'system_setting',
                    'menu_type' => 0,
                    'icon' => 'element-Setting',
                    'api_url' => '',
                    'router_path' => 'setting',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 49,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '平台菜单',
                            'menu_key' => 'platform_menu',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'sys/menu',
                            'router_path' => 'admin',
                            'view_path' => 'auth/menu',
                            'methods' => 'get',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                            'children' => [
                                [
                                    'menu_name' => '新增',
                                    'menu_key' => 'auth_menu_add',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/menu',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'post',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '编辑',
                                    'menu_key' => 'auth_menu_update',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/menu/<menu_key>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'put',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '删除',
                                    'menu_key' => 'auth_menu_del',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/menu',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'delete',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '详情',
                                    'menu_key' => 'auth_menu_info',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/menu/<menu_key>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'get',
                                    'sort' => 0,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                            ],
                        ],
                        [
                            'menu_name' => '站点菜单',
                            'menu_key' => 'site_menu',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'sys/menu',
                            'router_path' => 'site',
                            'view_path' => 'auth/site_menu',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 1,
                            'children' => [
                                [
                                    'menu_name' => '新增',
                                    'menu_key' => 'auth_site_menu_add',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/menu',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'post',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '编辑',
                                    'menu_key' => 'auth_site_menu_update',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/menu/<menu_key>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'put',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '删除',
                                    'menu_key' => 'auth_site_menu_del',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/menu',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'delete',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '详情',
                                    'menu_key' => 'auth_site_menu_info',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/menu/<menu_key>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'get',
                                    'sort' => 0,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                            ],
                        ]
                    ]
                ],
                [
                    'menu_name' => '计划任务',
                    'menu_key' => 'tools_schedule',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconjihuarenwu',
                    'api_url' => 'sys/schedule/list',
                    'router_path' => 'schedule',
                    'view_path' => 'tools/schedule',
                    'methods' => '',
                    'sort' => 40,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '新增',
                            'menu_key' => 'schedule_add',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/schedule',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'post',
                            'sort' => 4,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '编辑',
                            'menu_key' => 'schedule_update',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/schedule/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'put',
                            'sort' => 3,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '设置状态',
                            'menu_key' => 'schedule_set_status',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'schedule/modify/status/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'put',
                            'sort' => 2,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '删除',
                            'menu_key' => 'schedule_del',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/schedule/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'delete',
                            'sort' => 1,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '授权信息',
                    'menu_key' => 'app_auth',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconshouquanxinxi2',
                    'api_url' => 'niucloud/authinfo',
                    'router_path' => 'authorize',
                    'view_path' => 'app/authorize',
                    'methods' => 'get',
                    'sort' => 30,
                    'status' => 1,
                    'is_show' => 1
                ],
                [
                    'menu_name' => '开发者key',
                    'menu_key' => 'developer_token',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconshouquanxinxi2',
                    'api_url' => 'sys/config/developer_token',
                    'router_path' => 'developer_token',
                    'view_path' => 'setting/developer_token',
                    'methods' => 'get',
                    'sort' => 20,
                    'status' => 1,
                    'is_show' => 1
                ]
            ]
        ],
        [
            'menu_name' => '应用市场',
            'menu_key' => 'app_store',
            'menu_type' => 1,
            'icon' => 'element-ShoppingBag',
            'api_url' => 'addon/local',
            'router_path' => 'app_store',
            'view_path' => 'app/store',
            'methods' => 'get',
            'sort' => 0,
            'status' => 1,
            'is_show' => 1
        ]
    ];
