<?php
return
    [
        [
            'menu_name' => '控制台',
            'menu_key' => 'overview',
            'menu_type' => 1,
            'icon' => 'element-Monitor',
            'api_url' => '',
            'router_path' => 'siteindex',
            'view_path' => 'index/site_index',
            'methods' => '',
            'sort' => 100,
            'status' => 1,
            'is_show' => 1,
        ],
        [
            'menu_name' => '装修管理',
            'menu_key' => 'diy',
            'menu_type' => 0,
            'icon' => 'element-Brush',
            'api_url' => '',
            'router_path' => 'diy',
            'view_path' => '',
            'methods' => '',
            'sort' => 90,
            'status' => 1,
            'is_show' => 1,
            'children' => [
                [
                    'menu_name' => '首页装修',
                    'menu_key' => 'diy_page_index',
                    'menu_type' => 1,
                    'icon' => 'element-House',
                    'api_url' => '',
                    'router_path' => 'index',
                    'view_path' => 'diy/index',
                    'methods' => '',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '个人中心',
                    'menu_key' => 'diy_page_member',
                    'menu_type' => 1,
                    'icon' => 'element-ScaleToOriginal',
                    'api_url' => '',
                    'router_path' => 'member',
                    'view_path' => 'diy/member',
                    'methods' => '',
                    'sort' => 90,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '保存',
                    'menu_key' => 'diy_page_update',
                    'menu_type' => 2,
                    'icon' => '',
                    'api_url' => 'diy/diy',
                    'router_path' => '',
                    'view_path' => '',
                    'methods' => 'post',
                    'sort' => 80,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '页面管理',
                    'menu_key' => 'diy_page_list',
                    'menu_type' => 1,
                    'icon' => 'iconfont-icondianpuzhuangxiu',
                    'api_url' => 'diy/diy',
                    'router_path' => 'list',
                    'view_path' => 'diy/list',
                    'methods' => 'get',
                    'sort' => 70,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '底部导航',
                    'menu_key' => 'diy_bottom',
                    'menu_type' => 1,
                    'icon' => 'iconfont-icondibudaohang',
                    'api_url' => 'diy/bottom',
                    'router_path' => 'tabbar',
                    'view_path' => 'diy/tabbar',
                    'methods' => 'get',
                    'sort' => 60,
                    'status' => 1,
                    'is_show' => 1,
                    'children' =>
                        [
                            [
                                'menu_name' => '保存',
                                'menu_key' => 'diy_tabbar_update',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'diy/bottom',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => 100,
                                'status' => 1,
                                'is_show' => 1,
                            ],
                        ],
                ],
                [
                    'menu_name' => '素材管理',
                    'menu_key' => 'attachment',
                    'menu_type' => 1,
                    'icon' => 'element-Files',
                    'api_url' => 'sys/attachment',
                    'router_path' => 'attachment',
                    'view_path' => 'tools/attachment',
                    'methods' => 'get',
                    'sort' => 50,
                    'status' => 1,
                    'is_show' => 1,
                ]
            ]
        ],
        [
            'menu_name' => '页面装修',
            'menu_key' => 'decorate',
            'menu_type' => 0,
            'icon' => '',
            'api_url' => '',
            'router_path' => 'decorate',
            'view_path' => '',
            'methods' => '',
            'sort' => 21,
            'status' => 1,
            'is_show' => 0,
            'children' => [
                [
                    'menu_name' => '装修',
                    'menu_key' => 'page_decorate',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => 'diy/diy/<id>',
                    'router_path' => 'edit',
                    'view_path' => 'diy/edit',
                    'methods' => 'put',
                    'sort' => 0,
                    'status' => 1,
                    'is_show' => 0,
                ]
            ]
        ],
        [

            'menu_name' => '文章管理',
            'menu_key' => 'article',
            'menu_type' => 0,
            'icon' => 'element-Tickets',
            'api_url' => '',
            'router_path' => 'article',
            'view_path' => '',
            'methods' => '',
            'sort' => 80,
            'status' => 1,
            'is_show' => 1,
            'children' => [
                [
                    'menu_name' => '文章列表',
                    'menu_key' => 'article_list',
                    'menu_type' => 1,
                    'icon' => 'element-ChatDotSquare',
                    'api_url' => 'article/article',
                    'router_path' => 'list',
                    'view_path' => 'article/list',
                    'methods' => 'get',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '文章添加/编辑',
                    'menu_key' => 'article_edit',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => 'article/article',
                    'router_path' => 'edit',
                    'view_path' => 'article/edit',
                    'methods' => 'post',
                    'sort' => 90,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '文章栏目',
                    'menu_key' => 'article_category',
                    'menu_type' => 1,
                    'icon' => 'element-CollectionTag',
                    'api_url' => 'article/category',
                    'router_path' => 'category',
                    'view_path' => 'article/category',
                    'methods' => 'get',
                    'sort' => 80,
                    'status' => 1,
                    'is_show' => 1,
                ],
            ]
        ],
        [
            'menu_name' => '会员管理',
            'menu_key' => 'member',
            'menu_type' => 0,
            'icon' => 'iconfont-iconjiaoseyonghu',
            'api_url' => '',
            'router_path' => 'member',
            'view_path' => '',
            'methods' => '',
            'sort' => 70,
            'status' => 1,
            'is_show' => 1,
            'children' =>
                [
                    [
                        'menu_name' => '会员列表',
                        'menu_key' => 'member_list',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconhuiyuanliebiao',
                        'api_url' => 'member/member',
                        'router_path' => 'member',
                        'view_path' => 'member/member',
                        'methods' => 'get',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'children' => [
                            [

                                'menu_name' => '编辑',
                                'menu_key' => 'member_update',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'member/modify/<member_id>/<field>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => 0,
                                'status' => 1,
                                'is_show' => 1,
                            ],
                        ]
                    ],
                    [
                        'menu_name' => '会员详情',
                        'menu_key' => 'member_info',
                        'menu_type' => 1,
                        'icon' => '',
                        'api_url' => 'member/member/<id>',
                        'router_path' => 'detail',
                        'view_path' => 'member/member_detail',
                        'methods' => 'get',
                        'sort' => 90,
                        'status' => 1,
                        'is_show' => 0,
                    ],
                    [
                        'menu_name' => '会员标签',
                        'menu_key' => 'member_label',
                        'menu_type' => 1,
                        'icon' => 'element-CollectionTag',
                        'api_url' => 'member/label',
                        'router_path' => 'label',
                        'view_path' => 'member/label',
                        'methods' => 'get',
                        'sort' => 80,
                        'status' => 1,
                        'is_show' => 1,
                        'children' => [
                            [

                                'menu_name' => '编辑标签',
                                'menu_key' => 'member_label_update',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'member/label/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => 0,
                                'status' => 1,
                                'is_show' => 1,
                            ],
                            [

                                'menu_name' => '添加标签',
                                'menu_key' => 'member_label_add',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'member/label',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => 0,
                                'status' => 1,
                                'is_show' => 1,
                            ],
                            [

                                'menu_name' => '删除标签',
                                'menu_key' => 'member_label_delete',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'member/label/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => 0,
                                'status' => 1,
                                'is_show' => 1,
                            ],
                        ]
                    ],
                    [
                        'menu_name' => '会员积分',
                        'menu_key' => 'member_point',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconjifen-xianxing',
                        'api_url' => 'member/account/point',
                        'router_path' => 'point',
                        'view_path' => 'member/point',
                        'methods' => 'get',
                        'sort' => 70,
                        'status' => 1,
                        'is_show' => 1,
                    ],
                    [
                        'menu_name' => '会员余额',
                        'menu_key' => 'member_balance',
                        'menu_type' => 1,
                        'icon' => 'element-Money',
                        'api_url' => 'member/account/balance',
                        'router_path' => 'balance',
                        'view_path' => 'member/balance',
                        'methods' => 'get',
                        'sort' => 60,
                        'status' => 1,
                        'is_show' => 1,
                    ],
                    [
                        'menu_name' => '会员佣金',
                        'menu_key' => 'member_commission',
                        'menu_type' => 1,
                        'icon' => 'element-Money',
                        'api_url' => 'member/account/commission',
                        'router_path' => 'commission',
                        'view_path' => 'member/commission',
                        'methods' => 'get',
                        'sort' => 59,
                        'status' => 1,
                        'is_show' => 1,
                    ],
                ],
        ],
        [
            'menu_name' => '订单管理',
            'menu_key' => 'order',
            'menu_type' => 0,
            'icon' => 'iconfont-icondingdan',
            'api_url' => '',
            'router_path' => 'order',
            'view_path' => '',
            'methods' => '',
            'sort' => 65,
            'status' => 1,
            'is_show' => 1,
            'children' => [
                [
                    'menu_name' => '充值订单',
                    'menu_key' => 'recharge_order',
                    'menu_type' => 0,
                    'icon' => 'element-Help',
                    'api_url' => 'recharge',
                    'router_path' => 'recharge',
                    'view_path' => '',
                    'methods' => 'get',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '订单列表',
                            'menu_key' => 'recharge_order_list',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'recharge',
                            'router_path' => 'order',
                            'view_path' => 'order/recharge/list',
                            'methods' => 'get',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                            'children' => [
                                [
                                    'menu_name' => '退款',
                                    'menu_key' => 'recharge_refund',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'order/refund/<id>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'put',
                                    'sort' => 100,
                                    'status' => 1,
                                    'is_show' => 0,
                                ],
                            ]
                        ],
                        [
                            'menu_name' => '订单详情',
                            'menu_key' => 'recharge_order_detail',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'order/recharge/<order_id>',
                            'router_path' => 'detail',
                            'view_path' => 'order/recharge/detail',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                        [
                            'menu_name' => '退款记录',
                            'menu_key' => 'recharge_refund_list',
                            'menu_type' => 1,
                            'icon' => 'iconfont-icontuikuanjilu',
                            'api_url' => 'order/refund',
                            'router_path' => 'refund',
                            'view_path' => 'order/recharge/refund',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 1,
                            'children' => [
                                [
                                    'menu_name' => '退款详情',
                                    'menu_key' => 'recharge_refund_detail',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'order/refund/<id>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'get',
                                    'sort' => 100,
                                    'status' => 1,
                                    'is_show' => 0,
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ],
        [
            'menu_name' => '财务管理',
            'menu_key' => 'finance',
            'menu_type' => 0,
            'icon' => 'element-Box',
            'api_url' => '',
            'router_path' => 'finance',
            'view_path' => '',
            'methods' => '',
            'sort' => 60,
            'status' => 1,
            'is_show' => 1,
            'children' => [
                [
                    'menu_name' => '会员提现',
                    'menu_key' => 'cash_out_list',
                    'menu_type' => 1,
                    'icon' => 'element-Postcard',
                    'api_url' => 'member/cash_out',
                    'router_path' => 'cash_out',
                    'view_path' => 'finance/cash_out',
                    'methods' => 'get',
                    'sort' => 99,
                    'status' => 1,
                    'is_show' => 1,
                ]
            ]
        ],
        [

            'menu_name' => '应用管理',
            'menu_key' => 'addon',
            'menu_type' => 0,
            'icon' => 'iconfont-iconmanage-apply',
            'api_url' => '',
            'router_path' => 'app',
            'view_path' => '',
            'methods' => '',
            'sort' => 55,
            'status' => 1,
            'is_show' => 1,
            'children' => [
                [
                    'menu_name' => '应用管理',
                    'menu_key' => 'addon_list',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconmanage-apply',
                    'api_url' => 'addon/list',
                    'router_path' => 'index',
                    'view_path' => 'app/index',
                    'methods' => 'get',
                    'sort' => 50,
                    'status' => 1,
                    'is_show' => 1,
                ]
            ]
        ],
        [

            'menu_name' => '渠道管理',
            'menu_key' => 'channel',
            'menu_type' => 0,
            'icon' => 'element-DataBoard',
            'api_url' => '',
            'router_path' => 'channel',
            'view_path' => '',
            'methods' => '',
            'sort' => 50,
            'status' => 1,
            'is_show' => 1,
            'children' => [
                [
                    'menu_name' => '电脑端',
                    'menu_key' => 'channel_pc',
                    'menu_type' => 0,
                    'icon' => 'iconfont-icondesktop',
                    'api_url' => '',
                    'router_path' => 'pc',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '电脑端配置',
                            'menu_key' => 'pc_config',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => '',
                            'router_path' => 'config',
                            'view_path' => 'channel/pc/config',
                            'methods' => '',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => 'H5',
                    'menu_key' => 'channel_h5',
                    'menu_type' => 0,
                    'icon' => 'iconfont-iconh5e',
                    'api_url' => 'channel/h5/config',
                    'router_path' => 'h5',
                    'view_path' => '',
                    'methods' => 'get',
                    'sort' => 110,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => 'H5端配置',
                            'menu_key' => 'h5_config',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'channel/h5/config',
                            'router_path' => 'config',
                            'view_path' => 'channel/h5/config',
                            'methods' => 'put',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '微信公众号',
                    'menu_key' => 'channel_wechat',
                    'menu_type' => 0,
                    'icon' => 'iconfont-iconweixingongzhonghao1',
                    'api_url' => '',
                    'router_path' => 'wechat',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 90,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '公众号配置',
                            'menu_key' => 'wechat_config',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'wechat/config',
                            'router_path' => 'config',
                            'view_path' => 'channel/wechat/config',
                            'methods' => 'get',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '自定义菜单',
                            'menu_key' => 'wechat_menu',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'wechat/menu',
                            'router_path' => 'menu',
                            'view_path' => 'channel/wechat/menu',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '模板消息',
                            'menu_key' => 'wechat_template_message',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'wechat/template',
                            'router_path' => 'message',
                            'view_path' => 'channel/wechat/template',
                            'methods' => 'get',
                            'sort' => 70,
                            'status' => 1,
                            'is_show' => 1,
                        ]
                    ]
                ],
                [
                    'menu_name' => '微信小程序',
                    'menu_key' => 'channel_weapp',
                    'menu_type' => 0,
                    'icon' => 'iconfont-iconxiaochengxushezhi',
                    'api_url' => '',
                    'router_path' => 'weapp',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 80,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '小程序配置',
                            'menu_key' => 'weapp_config',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'weapp/config',
                            'router_path' => 'config',
                            'view_path' => 'channel/weapp/config',
                            'methods' => 'get',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '订阅消息',
                            'menu_key' => 'weapp_template_message',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'weapp/template',
                            'router_path' => 'message',
                            'view_path' => 'channel/weapp/template',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 1,
                        ]
                    ]
                ],
                [
                    'menu_name' => '支付宝小程序',
                    'menu_key' => 'channel_aliapp',
                    'menu_type' => 0,
                    'icon' => 'iconfont-iconzhifubao',
                    'api_url' => 'aliapp/config',
                    'router_path' => 'aliapp',
                    'view_path' => '',
                    'methods' => 'get',
                    'sort' => 70,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '支付宝配置',
                            'menu_key' => 'aliapp_config',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'aliapp/config',
                            'router_path' => 'config',
                            'view_path' => 'channel/aliapp/config',
                            'methods' => 'put',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
            ]
        ],
        [
            'menu_name' => '权限管理',
            'menu_key' => 'auth',
            'menu_type' => 0,
            'icon' => 'element-Lock',
            'api_url' => '',
            'router_path' => 'auth',
            'view_path' => '',
            'methods' => '',
            'sort' => 40,
            'status' => 1,
            'is_show' => 1,
            'children' => [
                [

                    'menu_name' => '管理员',
                    'menu_key' => 'auth_user',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconyonghu',
                    'api_url' => 'site/user',
                    'router_path' => 'user',
                    'view_path' => 'auth/user',
                    'methods' => 'get',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '新增',
                            'menu_key' => 'auth_user_add',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'site/user',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'post',
                            'sort' => 1,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '编辑',
                            'menu_key' => 'auth_user_update',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'site/user/<uid>',
                            'router_path' => '',
                            'view_path' => 'put',
                            'methods' => '',
                            'sort' => 1,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '删除',
                            'menu_key' => 'auth_user_del',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'site/user/<uid>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'delete',
                            'sort' => 1,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '详情',
                            'menu_key' => 'auth_user_info',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/user/<uid>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'get',
                            'sort' => 0,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ],
                ],
                [
                    'menu_name' => '角色管理',
                    'menu_key' => 'auth_role',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconhuiyuanliebiao',
                    'api_url' => 'sys/role',
                    'router_path' => 'role',
                    'view_path' => 'auth/role',
                    'methods' => 'get',
                    'sort' => 90,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '新增',
                            'menu_key' => 'auth_role_add',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/role',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'post',
                            'sort' => 1,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '编辑',
                            'menu_key' => 'auth_role_update',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/role/<role_id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'put',
                            'sort' => 1,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '删除',
                            'menu_key' => 'auth_role_del',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/role/<role_id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'delete',
                            'sort' => 1,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '操作日志',
                    'menu_key' => 'auth_log',
                    'menu_type' => 1,
                    'icon' => 'element-Document',
                    'api_url' => 'sys/log',
                    'router_path' => 'log',
                    'view_path' => 'auth/log',
                    'methods' => 'get',
                    'sort' => 80,
                    'status' => 1,
                    'is_show' => 1,
                ],
            ]
        ],

        [
            'menu_name' => '系统设置',
            'menu_key' => 'setting',
            'menu_type' => 0,
            'icon' => 'element-Setting',
            'api_url' => '',
            'router_path' => 'setting',
            'view_path' => '',
            'methods' => '',
            'sort' => 30,
            'status' => 1,
            'is_show' => 1,
            'children' => [
                [
                    'menu_name' => '网站设置',
                    'menu_key' => 'setting_system',
                    'menu_type' => 1,
                    'icon' => 'element-Basketball',
                    'api_url' => 'sys/config/website',
                    'router_path' => 'system',
                    'view_path' => 'setting/system',
                    'methods' => 'get',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                    
                ],
                [
                    'menu_name' => '协议管理',
                    'menu_key' => 'system_agreement',
                    'menu_type' => 1,
                    'icon' => 'element-Notebook',
                    'api_url' => 'sys/agreement',
                    'router_path' => 'agreement',
                    'view_path' => 'setting/agreement',
                    'methods' => 'get',
                    'sort' => 80,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [

                    ]
                ],
                [
                    'menu_name' => '协议编辑',
                    'menu_key' => 'system_agreement_edit',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => 'sys/agreement/<key>',
                    'router_path' => 'agreement/edit',
                    'view_path' => 'setting/agreement_edit',
                    'methods' => 'put',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '注册登录',
                    'menu_key' => 'setting_login_register',
                    'menu_type' => 1,
                    'icon' => 'iconfont-icondenglu',
                    'api_url' => 'member/config/login',
                    'router_path' => 'login',
                    'view_path' => 'setting/login',
                    'methods' => 'get',
                    'sort' => 70,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '会员设置',
                    'menu_key' => 'setting_member',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconjiaoseyonghu',
                    'api_url' => 'member/config/member',
                    'router_path' => 'member',
                    'view_path' => 'setting/member',
                    'methods' => 'get',
                    'sort' => 71,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '支付管理',
                    'menu_key' => 'setting_pay',
                    'menu_type' => 1,
                    'icon' => 'element-Wallet',
                    'api_url' => '',
                    'router_path' => 'pay',
                    'view_path' => '',
                    'methods' => 'get',
                    'sort' => 60,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '支付设置',
                            'menu_key' => 'setting_pay_channel',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'pay/channel/lists',
                            'router_path' => 'channel',
                            'view_path' => 'setting/pay',
                            'methods' => 'get',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                            'children' => [
                                [
                                    'menu_name' => '设置',
                                    'menu_key' => 'setting_pay_channel_set',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'pay/channel/set/<channel>/<type>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'post',
                                    'sort' => 100,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                            ]
                        ],
                        [
                            'menu_name' => '打款设置',
                            'menu_key' => 'setting_pay_transfer',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'pay/transfer',
                            'router_path' => 'transfer',
                            'view_path' => 'setting/transfer',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 1,
                            'children'  => [
                                [
                                    'menu_name' => '设置',
                                    'menu_key' => 'setting_pay_transfer_set',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'pay/transfer',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'post',
                                    'sort' => 90,
                                    'status' => 1,
                                    'is_show' => 1,
                                    
                                ],
                            ]
                        ],
//                        [
//                            'menu_name' => '微信支付',
//                            'menu_key' => 'setting_wechatpay',
//                            'menu_type' => 2,
//                            'icon' => '',
//                            'api_url' => '',
//                            'router_path' => 'wechatpay',
//                            'view_path' => '',
//                            'methods' => '',
//                            'sort' => 0,
//                            'status' => 1,
//                            'is_show' => 0,
//                            
//                        ],
//                        [
//                            'menu_name' => '支付宝支付',
//                            'menu_key' => 'setting_alipay',
//                            'menu_type' => 2,
//                            'icon' => '',
//                            'api_url' => '',
//                            'router_path' => 'alipay',
//                            'view_path' => '',
//                            'methods' => '',
//                            'sort' => 0,
//                            'status' => 1,
//                            'is_show' => 0,
//                            
//                        ],
//                        [
//                            'menu_name' => '获取支付配置',
//                            'menu_key' => 'set_pay_config',
//                            'menu_type' => 2,
//                            'icon' => '',
//                            'api_url' => 'pay/config/<type>',
//                            'router_path' => '',
//                            'view_path' => '',
//                            'methods' => 'get',
//                            'sort' => 0,
//                            'status' => 1,
//                            'is_show' => 0,
//                            
//                        ],
//                        [
//                            'menu_name' => '配置支付',
//                            'menu_key' => 'set_pay_config',
//                            'menu_type' => 2,
//                            'icon' => '',
//                            'api_url' => 'pay/config/<type>',
//                            'router_path' => '',
//                            'view_path' => '',
//                            'methods' => 'put',
//                            'sort' => 0,
//                            'status' => 1,
//                            'is_show' => 0,
//                            
//                        ],
                    ]
                ],
                [
                    'menu_name' => '提现设置',
                    'menu_key' => 'cash_out_config',
                    'menu_type' => 1,
                    'icon' => 'element-Postcard',
                    'api_url' => 'member/config/cash_out',
                    'router_path' => 'cash_out',
                    'view_path' => 'setting/cash_out',
                    'methods' => 'post',
                    'sort' => 59,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '消息管理',
                    'menu_key' => 'setting_notice',
                    'menu_type' => 1,
                    'icon' => 'element-ChatLineSquare',
                    'api_url' => '',
                    'router_path' => 'notice',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 50,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '消息模板',
                            'menu_key' => 'setting_notice_template',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'notice/notice',
                            'router_path' => 'template',
                            'view_path' => 'setting/notice',
                            'methods' => 'get',
                            'sort' => 10,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '发送记录',
                            'menu_key' => 'setting_notice_records',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'notice/notice/log',
                            'router_path' => 'records',
                            'view_path' => 'setting/notice_records',
                            'methods' => 'get',
                            'sort' => 9,
                            'status' => 1,
                            'is_show' => 1,
                        ]
                    ]
                ],
                [
                    'menu_name' => '短信管理',
                    'menu_key' => 'sms_notice',
                    'menu_type' => 0,
                    'icon' => 'element-Message',
                    'api_url' => '',
                    'router_path' => 'sms',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 40,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '短信设置',
                            'menu_key' => 'sms_setting',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'notice/sms',
                            'router_path' => 'setting',
                            'view_path' => 'setting/sms',
                            'methods' => 'get',
                            'sort' => 12,
                            'status' => 1,
                            'is_show' => 1,
                            
                        ],
                        [
                            'menu_name' => '发送记录',
                            'menu_key' => 'sms_notice_records',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'notice/sms/log',
                            'router_path' => 'records',
                            'view_path' => 'setting/sms_records',
                            'methods' => 'get',
                            'sort' => 11,
                            'status' => 1,
                            'is_show' => 1,

                        ]
                    ]
                ],
                [
                    'menu_name' => '地图设置',
                    'menu_key' => 'map_setting',
                    'menu_type' => 1,
                    'icon' => 'element-Message',
                    'api_url' => 'sys/config/map',
                    'router_path' => 'map',
                    'view_path' => 'setting/map',
                    'methods' => 'get',
                    'sort' => 99,
                    'status' => 1,
                    'is_show' => 1,
                ]
            ]
        ]
    ];