<?php
return [
    [
        'menu_name' => '装修管理',
        'menu_key' => 'diy',
        'menu_short_name' => '装修',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'element-Brush',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '90',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '编辑',
                'menu_key' => 'diy_tabbar_edit',
                'menu_short_name' => '编辑',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'diy/bottom/edit',
                'router_path' => 'diy/tabbar_edit',
                'view_path' => 'diy/tabbar_edit',
                'methods' => 'post',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '启动页',
                'menu_key' => 'diy_page_decorate_index',
                'menu_short_name' => '启动页',
                'menu_type' => '1',
                'icon' => 'element-House',
                'api_url' => '',
                'router_path' => 'diy/index',
                'view_path' => 'diy/index',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '个人中心',
                'menu_key' => 'diy_page_decorate_member_index',
                'menu_short_name' => '个人中心',
                'menu_type' => '1',
                'icon' => 'iconfont-iconhuiyuanliebiao',
                'api_url' => '',
                'router_path' => 'diy/member',
                'view_path' => 'diy/member',
                'methods' => '',
                'sort' => '99',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '保存',
                'menu_key' => 'diy_page_update',
                'menu_short_name' => '保存',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'diy/diy',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '95',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '微页面',
                'menu_key' => 'diy_page_list',
                'menu_short_name' => '微页面',
                'menu_type' => '1',
                'icon' => 'iconfont-icondianpuzhuangxiu',
                'api_url' => 'diy/diy',
                'router_path' => 'diy/list',
                'view_path' => 'diy/list',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '页面路径',
                'menu_key' => 'diy_page_route',
                'menu_short_name' => '页面路径',
                'menu_type' => '1',
                'icon' => 'iconfont-icondianpuzhuangxiu',
                'api_url' => 'diy/diy',
                'router_path' => 'diy/route',
                'view_path' => 'diy/route',
                'methods' => 'get',
                'sort' => '85',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '底部导航',
                'menu_key' => 'diy_bottom',
                'menu_short_name' => '底部导航',
                'menu_type' => '1',
                'icon' => 'iconfont-icondibudaohang',
                'api_url' => 'diy/bottom',
                'router_path' => 'diy/tabbar',
                'view_path' => 'diy/tabbar',
                'methods' => 'get',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '保存',
                        'menu_key' => 'diy_tabbar_update',
                        'menu_short_name' => '保存',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'diy/bottom',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '素材管理',
                'menu_key' => 'attachment',
                'menu_short_name' => '素材管理',
                'menu_type' => '1',
                'icon' => 'element-Files',
                'api_url' => 'sys/attachment',
                'router_path' => 'diy/attachment',
                'view_path' => 'tools/attachment',
                'methods' => 'get',
                'sort' => '75',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
    [
        'menu_name' => '会员管理',
        'menu_key' => 'member',
        'menu_short_name' => '会员',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont-iconjiaoseyonghu',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '70',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '会员列表',
                'menu_key' => 'member_list',
                'menu_short_name' => '会员列表',
                'menu_type' => '1',
                'icon' => 'iconfont-iconhuiyuanliebiao',
                'api_url' => 'member/member',
                'router_path' => 'member/member',
                'view_path' => 'member/member',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '编辑',
                        'menu_key' => 'member_update',
                        'menu_short_name' => '编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member/modify/<member_id>/<field>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '会员详情',
                'menu_key' => 'member_info',
                'menu_short_name' => '会员详情',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'member/member/<id>',
                'router_path' => 'member/detail',
                'view_path' => 'member/member_detail',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '会员标签',
                'menu_key' => 'member_label',
                'menu_short_name' => '会员标签',
                'menu_type' => '1',
                'icon' => 'element-CollectionTag',
                'api_url' => 'member/label',
                'router_path' => 'member/label',
                'view_path' => 'member/label',
                'methods' => 'get',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '编辑标签',
                        'menu_key' => 'member_label_update',
                        'menu_short_name' => '编辑标签',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member/label/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '添加标签',
                        'menu_key' => 'member_label_add',
                        'menu_short_name' => '添加标签',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member/label',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '删除标签',
                        'menu_key' => 'member_label_delete',
                        'menu_short_name' => '删除标签',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member/label/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '会员积分',
                'menu_key' => 'member_point',
                'menu_short_name' => '会员积分',
                'menu_type' => '1',
                'icon' => 'iconfont-iconjifen-xianxing',
                'api_url' => 'member/account/point',
                'router_path' => 'member/point',
                'view_path' => 'member/point',
                'methods' => 'get',
                'sort' => '70',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '会员余额',
                'menu_key' => 'member_balance',
                'menu_short_name' => '会员余额',
                'menu_type' => '1',
                'icon' => 'element-Money',
                'api_url' => 'member/account/balance',
                'router_path' => 'member/balance',
                'view_path' => 'member/balance',
                'methods' => 'get',
                'sort' => '60',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '会员佣金',
                'menu_key' => 'member_commission',
                'menu_short_name' => '会员佣金',
                'menu_type' => '1',
                'icon' => 'element-Money',
                'api_url' => 'member/account/commission',
                'router_path' => 'member/commission',
                'view_path' => 'member/commission',
                'methods' => 'get',
                'sort' => '59',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
    [
        'menu_name' => '财务管理',
        'menu_key' => 'finance',
        'menu_short_name' => '财务',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'element-Box',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '60',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '财务流水',
                'menu_key' => 'site_account_list',
                'menu_short_name' => '财务流水',
                'menu_type' => '1',
                'icon' => 'element-Postcard',
                'api_url' => 'finance/account',
                'router_path' => 'finance/account',
                'view_path' => 'finance/account',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '支付单据详情',
                'menu_key' => 'site_pay_detail',
                'menu_short_name' => '支付单据详情',
                'menu_type' => '1',
                'icon' => 'element-Postcard',
                'api_url' => 'pay/detail',
                'router_path' => 'finance/pay/detail',
                'view_path' => 'finance/pay_detail',
                'methods' => 'get',
                'sort' => '98',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '会员提现',
                'menu_key' => 'cash_out_list',
                'menu_short_name' => '会员提现',
                'menu_type' => '1',
                'icon' => 'element-Postcard',
                'api_url' => 'member/cash_out',
                'router_path' => 'finance/cash_out',
                'view_path' => 'finance/cash_out',
                'methods' => 'get',
                'sort' => '97',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '会员退款',
                'menu_key' => 'member_refund_list',
                'menu_short_name' => '会员退款',
                'menu_type' => '1',
                'icon' => 'iconfont-iconhuiyuantixian',
                'api_url' => 'pay/pay_refund',
                'router_path' => 'finance/refund',
                'view_path' => 'finance/pay_refund',
                'methods' => 'get',
                'sort' => '9',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '退款详情',
                'menu_key' => 'member_refund_detail',
                'menu_short_name' => '退款详情',
                'menu_type' => '1',
                'icon' => 'iconfont-iconhuiyuantixian',
                'api_url' => 'pay/refund',
                'router_path' => 'finance/refund/detail',
                'view_path' => 'finance/refund_detail',
                'methods' => 'get',
                'sort' => '9',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
    [
        'menu_name' => '应用管理',
        'menu_key' => 'addon',
        'menu_short_name' => '应用',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont-iconmanage-apply',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '55',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '应用管理',
                'menu_key' => 'addon_list',
                'menu_short_name' => '应用管理',
                'menu_type' => '1',
                'icon' => 'iconfont-iconmanage-apply',
                'api_url' => 'addon/list',
                'router_path' => 'app/index',
                'view_path' => 'app/index',
                'methods' => 'get',
                'sort' => '50',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
    [
        'menu_name' => '渠道管理',
        'menu_key' => 'channel',
        'menu_short_name' => '渠道',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'element-DataBoard',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '50',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '电脑端',
                'menu_key' => 'pc_config',
                'menu_short_name' => '电脑端',
                'menu_type' => '1',
                'icon' => 'iconfont-icondesktop',
                'api_url' => '',
                'router_path' => 'channel/pc/config',
                'view_path' => 'channel/pc/config',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => 'H5端',
                'menu_key' => 'h5_config',
                'menu_short_name' => 'H5端',
                'menu_type' => '1',
                'icon' => 'iconfont-iconh5e',
                'api_url' => 'channel/h5/config',
                'router_path' => 'channel/h5/config',
                'view_path' => 'channel/h5/config',
                'methods' => 'put',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '微信公众号',
                'menu_key' => 'channel_wechat',
                'menu_short_name' => '微信公众号',
                'menu_type' => '1',
                'icon' => 'iconfont-iconweixingongzhonghao1',
                'api_url' => 'wechat/access',
                'router_path' => 'channel/wechat',
                'view_path' => 'channel/wechat/access',
                'methods' => '',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '微信小程序',
                'menu_key' => 'weapp_access',
                'menu_short_name' => '微信小程序',
                'menu_type' => '1',
                'icon' => 'iconfont-iconxiaochengxushezhi',
                'api_url' => 'weapp/access',
                'router_path' => 'channel/weapp',
                'view_path' => 'channel/weapp/access',
                'methods' => 'get',
                'sort' => '70',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '支付宝小程序',
                'menu_key' => 'aliapp_weapp_access',
                'menu_short_name' => '支付宝小程序',
                'menu_type' => '1',
                'icon' => 'iconfont-iconzhifubao',
                'api_url' => 'aliapp/access',
                'router_path' => 'channel/aliapp',
                'view_path' => 'channel/aliapp/access',
                'methods' => 'get',
                'sort' => '60',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '发布教程',
                'menu_key' => 'wechat_course',
                'menu_short_name' => '发布教程',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'wechat/course',
                'router_path' => 'channel/wechat/course',
                'view_path' => 'channel/wechat/course',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '公众号配置',
                'menu_key' => 'wechat_config',
                'menu_short_name' => '公众号配置',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'wechat/config',
                'router_path' => 'channel/wechat/config',
                'view_path' => 'channel/wechat/config',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '自定义菜单',
                'menu_key' => 'wechat_menu',
                'menu_short_name' => '自定义菜单',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'wechat/menu',
                'router_path' => 'channel/wechat/menu',
                'view_path' => 'channel/wechat/menu',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '模板消息',
                'menu_key' => 'wechat_template_message',
                'menu_short_name' => '模板消息',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'wechat/template',
                'router_path' => 'channel/wechat/message',
                'view_path' => 'channel/wechat/template',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '配置教程',
                'menu_key' => 'weapp_course',
                'menu_short_name' => '配置教程',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'weapp/course',
                'router_path' => 'channel/weapp/course',
                'view_path' => 'channel/weapp/course',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '小程序配置',
                'menu_key' => 'weapp_config',
                'menu_short_name' => '小程序配置',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'weapp/config',
                'router_path' => 'channel/weapp/config',
                'view_path' => 'channel/weapp/config',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '订阅消息',
                'menu_key' => 'weapp_template_message',
                'menu_short_name' => '订阅消息',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'weapp/template',
                'router_path' => 'channel/weapp/message',
                'view_path' => 'channel/weapp/template',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '小程序发布',
                'menu_key' => 'weapp_code',
                'menu_short_name' => '小程序发布',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'weapp/code',
                'router_path' => 'channel/weapp/code',
                'view_path' => 'channel/weapp/code',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '支付宝配置',
                'menu_key' => 'aliapp_config',
                'menu_short_name' => '支付宝配置',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'aliapp/config',
                'router_path' => 'channel/aliapp/config',
                'view_path' => 'channel/aliapp/config',
                'methods' => 'put',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '配置教程',
                'menu_key' => 'aliapp_course',
                'menu_short_name' => '配置教程',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'aliapp/course',
                'router_path' => 'channel/aliapp/course',
                'view_path' => 'channel/aliapp/course',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
    [
        'menu_name' => '权限管理',
        'menu_key' => 'auth',
        'menu_short_name' => '权限',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'element-Lock',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '40',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '管理员',
                'menu_key' => 'auth_user',
                'menu_short_name' => '管理员',
                'menu_type' => '1',
                'icon' => 'iconfont-iconyonghu',
                'api_url' => 'site/user',
                'router_path' => 'auth/user',
                'view_path' => 'auth/user',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '新增',
                        'menu_key' => 'auth_user_add',
                        'menu_short_name' => '新增',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'site/user',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '编辑',
                        'menu_key' => 'auth_user_update',
                        'menu_short_name' => '编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'site/user/<uid>',
                        'router_path' => '',
                        'view_path' => 'put',
                        'methods' => '',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '删除',
                        'menu_key' => 'auth_user_del',
                        'menu_short_name' => '删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'site/user/<uid>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '详情',
                        'menu_key' => 'auth_user_info',
                        'menu_short_name' => '详情',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/user/<uid>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '角色管理',
                'menu_key' => 'auth_role',
                'menu_short_name' => '角色管理',
                'menu_type' => '1',
                'icon' => 'iconfont-iconhuiyuanliebiao',
                'api_url' => 'sys/role',
                'router_path' => 'auth/role',
                'view_path' => 'auth/role',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '新增',
                        'menu_key' => 'auth_role_add',
                        'menu_short_name' => '新增',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/role',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '编辑',
                        'menu_key' => 'auth_role_update',
                        'menu_short_name' => '编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/role/<role_id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '删除',
                        'menu_key' => 'auth_role_del',
                        'menu_short_name' => '删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'sys/role/<role_id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '操作日志',
                'menu_key' => 'auth_log',
                'menu_short_name' => '操作日志',
                'menu_type' => '1',
                'icon' => 'element-Document',
                'api_url' => 'sys/log',
                'router_path' => 'auth/log',
                'view_path' => 'auth/log',
                'methods' => 'get',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
    [
        'menu_name' => '系统设置',
        'menu_key' => 'setting',
        'menu_short_name' => '设置',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'element-Setting',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '30',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '网站设置',
                'menu_key' => 'setting_system',
                'menu_short_name' => '网站设置',
                'menu_type' => '1',
                'icon' => 'element-Basketball',
                'api_url' => 'sys/config/website',
                'router_path' => 'setting/system',
                'view_path' => 'setting/system',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '协议编辑',
                'menu_key' => 'system_agreement_edit',
                'menu_short_name' => '协议编辑',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'sys/agreement/<key>',
                'router_path' => 'setting/agreement/edit',
                'view_path' => 'setting/agreement_edit',
                'methods' => 'put',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '地图设置',
                'menu_key' => 'map_setting',
                'menu_short_name' => '地图设置',
                'menu_type' => '1',
                'icon' => 'element-Message',
                'api_url' => 'sys/config/map',
                'router_path' => 'setting/map',
                'view_path' => 'setting/map',
                'methods' => 'get',
                'sort' => '99',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '版权设置',
                'menu_key' => 'setting_copyright',
                'menu_short_name' => '版权设置',
                'menu_type' => '1',
                'icon' => 'iconfont-iconbanquan1',
                'api_url' => 'sys/config/copyright',
                'router_path' => 'setting/copyright',
                'view_path' => 'setting/copyright',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '协议管理',
                'menu_key' => 'system_agreement',
                'menu_short_name' => '协议管理',
                'menu_type' => '1',
                'icon' => 'element-Notebook',
                'api_url' => 'sys/agreement',
                'router_path' => 'setting/agreement',
                'view_path' => 'setting/agreement',
                'methods' => 'get',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '会员设置',
                'menu_key' => 'setting_member',
                'menu_short_name' => '会员设置',
                'menu_type' => '1',
                'icon' => 'iconfont-iconjiaoseyonghu',
                'api_url' => 'member/config/member',
                'router_path' => 'setting/member',
                'view_path' => 'setting/member',
                'methods' => 'get',
                'sort' => '71',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '注册登录',
                'menu_key' => 'setting_login_register',
                'menu_short_name' => '注册登录',
                'menu_type' => '1',
                'icon' => 'iconfont-iconzhuceshezhi',
                'api_url' => 'member/config/login',
                'router_path' => 'setting/login',
                'view_path' => 'setting/login',
                'methods' => 'get',
                'sort' => '70',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '支付管理',
                'menu_key' => 'setting_pay',
                'menu_short_name' => '支付管理',
                'menu_type' => '1',
                'icon' => 'element-Wallet',
                'api_url' => '',
                'router_path' => 'setting/pay',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '60',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '支付设置',
                        'menu_key' => 'setting_pay_channel',
                        'menu_short_name' => '支付设置',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'pay/channel/lists',
                        'router_path' => 'setting/pay/channel',
                        'view_path' => 'setting/pay',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '设置',
                                'menu_key' => 'setting_pay_channel_set',
                                'menu_short_name' => '设置',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'pay/channel/set/<channel>/<type>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '打款设置',
                        'menu_key' => 'setting_pay_transfer',
                        'menu_short_name' => '打款设置',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'pay/transfer',
                        'router_path' => 'setting/pay/transfer',
                        'view_path' => 'setting/transfer',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '设置',
                                'menu_key' => 'setting_pay_transfer_set',
                                'menu_short_name' => '设置',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'pay/transfer',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '90',
                                'status' => '1',
                                'is_show' => '1',
                            ],
                        ],
                    ],
                ],
            ],
            [
                'menu_name' => '提现设置',
                'menu_key' => 'cash_out_config',
                'menu_short_name' => '提现设置',
                'menu_type' => '1',
                'icon' => 'element-Postcard',
                'api_url' => 'member/config/cash_out',
                'router_path' => 'setting/cash_out',
                'view_path' => 'setting/cash_out',
                'methods' => 'post',
                'sort' => '59',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '消息管理',
                'menu_key' => 'setting_notice',
                'menu_short_name' => '消息管理',
                'menu_type' => '1',
                'icon' => 'element-ChatLineSquare',
                'api_url' => '',
                'router_path' => 'setting/notice',
                'view_path' => '',
                'methods' => '',
                'sort' => '50',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '消息模板',
                        'menu_key' => 'setting_notice_template',
                        'menu_short_name' => '消息模板',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'notice/notice',
                        'router_path' => 'setting/notice/template',
                        'view_path' => 'setting/notice',
                        'methods' => 'get',
                        'sort' => '10',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '发送记录',
                        'menu_key' => 'setting_notice_records',
                        'menu_short_name' => '发送记录',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'notice/notice/log',
                        'router_path' => 'setting/notice/records',
                        'view_path' => 'setting/notice_records',
                        'methods' => 'get',
                        'sort' => '9',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '短信管理',
                'menu_key' => 'sms_notice',
                'menu_short_name' => '短信管理',
                'menu_type' => '0',
                'icon' => 'element-Message',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '40',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '短信设置',
                        'menu_key' => 'sms_setting',
                        'menu_short_name' => '短信设置',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'notice/sms',
                        'router_path' => 'setting/sms/setting',
                        'view_path' => 'setting/sms',
                        'methods' => 'get',
                        'sort' => '12',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '发送记录',
                        'menu_key' => 'sms_notice_records',
                        'menu_short_name' => '发送记录',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'notice/sms/log',
                        'router_path' => 'setting/sms/records',
                        'view_path' => 'setting/sms_records',
                        'methods' => 'get',
                        'sort' => '11',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '存储设置',
                'menu_key' => 'setting_storage',
                'menu_short_name' => '存储设置',
                'menu_type' => '1',
                'icon' => 'element-FolderChecked',
                'api_url' => 'sys/storage',
                'router_path' => 'setting/storage',
                'view_path' => 'setting/storage',
                'methods' => 'get',
                'sort' => '30',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
    [
        'menu_name' => '页面装修',
        'menu_key' => 'decorate',
        'menu_short_name' => '页面装修',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => '',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '21',
        'status' => '1',
        'is_show' => '0',
        'children' => [
            [
                'menu_name' => '装修',
                'menu_key' => 'page_decorate',
                'menu_short_name' => '装修',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'diy/diy/<id>',
                'router_path' => 'decorate/edit',
                'view_path' => 'diy/edit',
                'methods' => 'put',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
    [
        'menu_name' => '页面预览',
        'menu_key' => 'preview',
        'menu_short_name' => '页面预览',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => '',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => 'get',
        'sort' => '0',
        'status' => '1',
        'is_show' => '0',
        'children' => [
            [
                'menu_name' => '页面预览',
                'menu_key' => 'page_wap_preview',
                'menu_short_name' => '页面预览',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'preview/wap',
                'view_path' => 'index/preview',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];