<?php

    return
        [
            [
                'menu_name' => '控制台',
                'menu_key' => 'overview',
                'menu_type' => 1,
                'icon' => 'element-Monitor',
                'api_url' => '',
                'router_path' => 'index',
                'view_path' => 'index/index',
                'methods' => '',
                'sort' => 100,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
            ],
            [
                'menu_name' => '站点管理',
                'menu_key' => 'site',
                'menu_type' => 0,
                'icon' => 'element-Memo',
                'api_url' => '',
                'router_path' => 'site',
                'view_path' => '',
                'methods' => '',
                'sort' => 50,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '站点列表',
                        'menu_key' => 'site_list',
                        'menu_type' => 1,
                        'icon' => 'element-OfficeBuilding',
                        'api_url' => 'site/site',
                        'router_path' => 'list',
                        'view_path' => 'site/list',
                        'methods' => 'get',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '站点详情',
                        'menu_key' => 'site_info',
                        'menu_type' => 1,
                        'icon' => '',
                        'api_url' => 'site/site/<site_id>',
                        'router_path' => 'info',
                        'view_path' => 'site/info',
                        'methods' => 'get',
                        'sort' => 90,
                        'status' => 1,
                        'is_show' => 0,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '站点套餐',
                        'menu_key' => 'site_group',
                        'menu_type' => 1,
                        'icon' => 'element-PriceTag',
                        'api_url' => 'site/group',
                        'router_path' => 'group',
                        'view_path' => 'site/group',
                        'methods' => 'get',
                        'sort' => 80,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '站点用户',
                        'menu_key' => 'site_user',
                        'menu_type' => 1,
                        'icon' => 'element-User',
                        'api_url' => 'user/user',
                        'router_path' => 'user',
                        'view_path' => 'site/user',
                        'methods' => 'get',
                        'sort' => 70,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ]
                ]
            ],
            [
                'menu_name' => '权限管理',
                'menu_key' => 'auth',
                'menu_type' => 0,
                'icon' => 'element-Lock',
                'api_url' => '',
                'router_path' => 'auth',
                'view_path' => '',
                'methods' => '',
                'sort' => 40,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '菜单管理',
                        'menu_key' => 'menu_list',
                        'menu_type' => 1,
                        'icon' => 'element-Operation',
                        'api_url' => '',
                        'router_path' => 'menu',
                        'view_path' => '',
                        'methods' => '',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [
                            [
                                'menu_name' => '平台菜单',
                                'menu_key' => 'auth_menu',
                                'menu_type' => 1,
                                'icon' => '',
                                'api_url' => 'sys/menu',
                                'router_path' => 'admin',
                                'view_path' => 'auth/menu',
                                'methods' => 'get',
                                'sort' => 100,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                                'children' => [
                                    [
                                        'menu_name' => '新增',
                                        'menu_key' => 'auth_menu_add',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => 'sys/menu',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => 'post',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '编辑',
                                        'menu_key' => 'auth_menu_update',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => 'sys/menu/<menu_key>',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => 'put',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '删除',
                                        'menu_key' => 'auth_menu_del',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => 'sys/menu',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => 'delete',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '详情',
                                        'menu_key' => 'auth_menu_info',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => 'sys/menu/<menu_key>',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => 'get',
                                        'sort' => 0,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                ],
                            ],
                            [
                                'menu_name' => '站点菜单',
                                'menu_key' => 'auth_site_menu',
                                'menu_type' => 1,
                                'icon' => '',
                                'api_url' => 'sys/menu',
                                'router_path' => 'site',
                                'view_path' => 'auth/site_menu',
                                'methods' => 'get',
                                'sort' => 90,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                                'children' => [
                                    [
                                        'menu_name' => '新增',
                                        'menu_key' => 'auth_site_menu_add',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => 'sys/menu',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => 'post',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '编辑',
                                        'menu_key' => 'auth_site_menu_update',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => 'sys/menu/<menu_key>',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => 'put',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '删除',
                                        'menu_key' => 'auth_site_menu_del',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => 'sys/menu',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => 'delete',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '详情',
                                        'menu_key' => 'auth_site_menu_info',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => 'sys/menu/<menu_key>',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => 'get',
                                        'sort' => 0,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                ],
                            ]
                        ]
                    ],
                    [

                        'menu_name' => '管理员',
                        'menu_key' => 'auth_user',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconyonghu',
                        'api_url' => 'site/user',
                        'router_path' => 'user',
                        'view_path' => 'auth/user',
                        'methods' => 'get',
                        'sort' => 80,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [
                            [
                                'menu_name' => '新增',
                                'menu_key' => 'auth_user_add',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'site/user',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '编辑',
                                'menu_key' => 'auth_user_update',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'site/user/<uid>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '删除',
                                'menu_key' => 'auth_user_del',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'site/user/<uid>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '详情',
                                'menu_key' => 'auth_user_info',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'sys/user/<uid>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => 0,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '角色管理',
                        'menu_key' => 'auth_role',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconhuiyuanliebiao',
                        'api_url' => 'sys/role',
                        'router_path' => 'role',
                        'view_path' => 'auth/role',
                        'methods' => 'get',
                        'sort' => 70,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [
                            [
                                'menu_name' => '新增',
                                'menu_key' => 'auth_role_add',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'sys/role',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '编辑',
                                'menu_key' => 'auth_role_update',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'sys/role/<role_id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '删除',
                                'menu_key' => 'auth_role_del',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'sys/role/<role_id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                        ]
                    ],
                    [
                        'menu_name' => '操作日志',
                        'menu_key' => 'auth_log',
                        'menu_type' => 1,
                        'icon' => 'element-Document',
                        'api_url' => 'sys/log',
                        'router_path' => 'log',
                        'view_path' => 'auth/log',
                        'methods' => 'get',
                        'sort' => 60,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                ]
            ],

            [
                'menu_name' => '系统设置',
                'menu_key' => 'setting',
                'menu_type' => 0,
                'icon' => 'element-Setting',
                'api_url' => '',
                'router_path' => 'setting',
                'view_path' => '',
                'methods' => '',
                'sort' => 20,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '网站设置',
                        'menu_key' => 'setting_system',
                        'menu_type' => 1,
                        'icon' => 'element-Basketball',
                        'api_url' => 'sys/config/website',
                        'router_path' => 'system',
                        'view_path' => 'setting/system',
                        'methods' => 'get',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '版权设置',
                        'menu_key' => 'setting_copyright',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconbanquan1',
                        'api_url' => 'sys/config/copyright',
                        'router_path' => 'copyright',
                        'view_path' => 'setting/copyright',
                        'methods' => 'get',
                        'sort' => 90,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '登录设置',
                        'menu_key' => 'setting_login',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconzhuceshezhi',
                        'api_url' => 'sys/config/login',
                        'router_path' => 'adminlogin',
                        'view_path' => 'setting/adminlogin',
                        'methods' => 'get',
                        'sort' => 80,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '存储设置',
                        'menu_key' => 'setting_storage',
                        'menu_type' => 1,
                        'icon' => 'element-FolderChecked',
                        'api_url' => 'sys/storage',
                        'router_path' => 'storage',
                        'view_path' => 'setting/storage',
                        'methods' => 'get',
                        'sort' => 30,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ]
                ]
            ],
            [
                'menu_name' => '开发工具',
                'menu_key' => 'tool',
                'menu_type' => 0,
                'icon' => 'element-Edit',
                'api_url' => '',
                'router_path' => 'tools',
                'view_path' => '',
                'methods' => '',
                'sort' => 10,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '代码生成',
                        'menu_key' => 'code',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconyuandaima',
                        'api_url' => 'generator/generator',
                        'router_path' => 'code',
                        'view_path' => 'tools/code/index',
                        'methods' => 'get',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '应用市场',
                        'menu_key' => 'app_store',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconyingyongshichang',
                        'api_url' => 'addon/local',
                        'router_path' => 'app_store',
                        'view_path' => 'tools/app/index',
                        'methods' => 'get',
                        'sort' => 90,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '数据表编辑',
                        'menu_key' => 'code_edit',
                        'menu_type' => 1,
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'code/edit',
                        'view_path' => 'tools/code/edit',
                        'methods' => '',
                        'sort' => 80,
                        'status' => 1,
                        'is_show' => 0,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '定时任务',
                        'menu_key' => 'system_cron',
                        'menu_type' => 1,
                        'icon' => 'element-SetUp',
                        'api_url' => 'sys/cron',
                        'router_path' => 'cron',
                        'view_path' => 'tools/cron',
                        'methods' => 'get',
                        'sort' => 70,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '更新缓存',
                        'menu_key' => 'tools_Update_cache',
                        'menu_type' => 1,
                        'icon' => 'iconfont-icongengxinhuancun',
                        'api_url' => '',
                        'router_path' => 'update',
                        'view_path' => 'tools/updatecache',
                        'methods' => '',
                        'sort' => 60,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '环境检测',
                        'menu_key' => 'iconfont-iconsixingjiance',
                        'menu_type' => 1,
                        'icon' => 'element-SetUp',
                        'api_url' => '',
                        'router_path' => 'detection',
                        'view_path' => 'tools/detection',
                        'methods' => '',
                        'sort' => 50,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ]
                ]
            ]
        ];