<?php

    return
        [
            [
                'menu_name' => '控制台',
                'menu_key' => 'overview',
                'menu_type' => 1,
                'icon' => 'element-Monitor',
                'api_url' => '',
                'router_path' => 'index',
                'view_path' => 'index/index',
                'methods' => '',
                'sort' => 100,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
            ],
            [
                'menu_name' => '装修管理',
                'menu_key' => 'diy',
                'menu_type' => 0,
                'icon' => 'element-Brush',
                'api_url' => '',
                'router_path' => 'diy',
                'view_path' => '',
                'methods' => '',
                'sort' => 90,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '首页装修',
                        'menu_key' => 'diy_page_index',
                        'menu_type' => 1,
                        'icon' => 'element-House',
                        'api_url' => '',
                        'router_path' => 'index',
                        'view_path' => 'diy/index',
                        'methods' => '',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '个人中心',
                        'menu_key' => 'diy_page_member',
                        'menu_type' => 1,
                        'icon' => 'element-ScaleToOriginal',
                        'api_url' => '',
                        'router_path' => 'member',
                        'view_path' => 'diy/member',
                        'methods' => '',
                        'sort' => 90,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '保存',
                        'menu_key' => 'diy_page_update',
                        'menu_type' => 2,
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => '',
                        'sort' => 80,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '页面管理',
                        'menu_key' => 'diy_page_list',
                        'menu_type' => 1,
                        'icon' => 'iconfont-icondianpuzhuangxiu',
                        'api_url' => '',
                        'router_path' => 'list',
                        'view_path' => 'diy/list',
                        'methods' => '',
                        'sort' => 70,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '底部导航',
                        'menu_key' => 'diy_bottom',
                        'menu_type' => 1,
                        'icon' => 'iconfont-icondibudaohang',
                        'api_url' => '',
                        'router_path' => 'tabbar',
                        'view_path' => 'diy/tabbar',
                        'methods' => '',
                        'sort' => 60,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [
                            [
                                'menu_name' => '保存',
                                'menu_key' => 'diy_tabbar_update',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => '',
                                'sort' => 100,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '素材管理',
                        'menu_key' => 'attachment',
                        'menu_type' => 1,
                        'icon' => 'element-Files',
                        'api_url' => '',
                        'router_path' => 'attachment',
                        'view_path' => 'tools/attachment',
                        'methods' => '',
                        'sort' => 50,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ]
                ],
            ],
            [
                'menu_name' => '装修管理',
                'menu_key' => 'decorate',
                'menu_type' => 0,
                'icon' => 'element-Brush',
                'api_url' => '',
                'router_path' => 'decorate',
                'view_path' => '',
                'methods' => '',
                'sort' => 90,
                'status' => 1,
                'is_show' => 0,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '装修',
                        'menu_key' => 'page_decorate',
                        'menu_type' => 1,
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'edit',
                        'view_path' => 'diy/edit',
                        'methods' => '',
                        'sort' => 0,
                        'status' => 1,
                        'is_show' => 0,
                        'en_menu_name' => '',
                    ]
                ]
            ],
            [
                'menu_name' => '文章管理',
                'menu_key' => 'article',
                'menu_type' => 0,
                'icon' => 'element-Tickets',
                'api_url' => '',
                'router_path' => 'article',
                'view_path' => '',
                'methods' => '',
                'sort' => 80,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '文章列表',
                        'menu_key' => 'article_list',
                        'menu_type' => 1,
                        'icon' => 'element-ChatDotSquare',
                        'api_url' => '',
                        'router_path' => 'list',
                        'view_path' => 'article/list',
                        'methods' => '',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '文章添加/编辑',
                        'menu_key' => 'article_edit',
                        'menu_type' => 1,
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'edit',
                        'view_path' => 'article/edit',
                        'methods' => '',
                        'sort' => 90,
                        'status' => 1,
                        'is_show' => 0,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '文章栏目',
                        'menu_key' => 'article_category',
                        'menu_type' => 1,
                        'icon' => 'element-CollectionTag',
                        'api_url' => '',
                        'router_path' => 'category',
                        'view_path' => 'article/category',
                        'methods' => '',
                        'sort' => 80,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                ]
            ],
            [
                'menu_name' => '会员管理',
                'menu_key' => 'member',
                'menu_type' => 0,
                'icon' => 'iconfont-iconjiaoseyonghu',
                'api_url' => '',
                'router_path' => 'member',
                'view_path' => '',
                'methods' => '',
                'sort' => 70,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' =>
                    [
                        [
                            'menu_name' => '会员列表',
                            'menu_key' => 'member_list',
                            'menu_type' => 1,
                            'icon' => 'iconfont-iconhuiyuanliebiao',
                            'api_url' => '',
                            'router_path' => 'member',
                            'view_path' => 'member/member',
                            'methods' => '',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                            'en_menu_name' => '',
                            'children' => [
                                [

                                    'menu_name' => '编辑',
                                    'menu_key' => 'member_update',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => '',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => '',
                                    'sort' => 0,
                                    'status' => 1,
                                    'is_show' => 1,
                                    'en_menu_name' => '',
                                ],
                            ]
                        ],
                        [
                            'menu_name' => '会员详情',
                            'menu_key' => 'member_info',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => '',
                            'router_path' => 'detail',
                            'view_path' => 'member/member_detail',
                            'methods' => '',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 0,
                            'en_menu_name' => '',
                        ],
                        [
                            'menu_name' => '会员标签',
                            'menu_key' => 'member_label',
                            'menu_type' => 1,
                            'icon' => 'element-CollectionTag',
                            'api_url' => '',
                            'router_path' => 'label',
                            'view_path' => 'member/label',
                            'methods' => '',
                            'sort' => 80,
                            'status' => 1,
                            'is_show' => 1,
                            'en_menu_name' => '',
                            'children' => [
                                [

                                    'menu_name' => '编辑标签',
                                    'menu_key' => 'member_label_update',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => '',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => '',
                                    'sort' => 0,
                                    'status' => 1,
                                    'is_show' => 1,
                                    'en_menu_name' => '',
                                ],
                                [

                                    'menu_name' => '添加标签',
                                    'menu_key' => 'member_label_add',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => '',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => '',
                                    'sort' => 0,
                                    'status' => 1,
                                    'is_show' => 1,
                                    'en_menu_name' => '',
                                ],
                                [

                                    'menu_name' => '删除标签',
                                    'menu_key' => 'member_label_add',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => '',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => '',
                                    'sort' => 0,
                                    'status' => 1,
                                    'is_show' => 1,
                                    'en_menu_name' => '',
                                ],
                            ]
                        ],
                        [
                            'menu_name' => '会员积分',
                            'menu_key' => 'member_point',
                            'menu_type' => 1,
                            'icon' => 'iconfont-iconjifen-xianxing',
                            'api_url' => '',
                            'router_path' => 'point',
                            'view_path' => 'member/point',
                            'methods' => '',
                            'sort' => 70,
                            'status' => 1,
                            'is_show' => 1,
                            'en_menu_name' => '',
                        ],
                        [
                            'menu_name' => '会员余额',
                            'menu_key' => 'member_balance',
                            'menu_type' => 1,
                            'icon' => 'element-Money',
                            'api_url' => '',
                            'router_path' => 'balance',
                            'view_path' => 'member/balance',
                            'methods' => '',
                            'sort' => 60,
                            'status' => 1,
                            'is_show' => 1,
                            'en_menu_name' => '',
                        ],
                        [
                            'menu_name' => '会员零钱',
                            'menu_key' => 'member_money',
                            'menu_type' => 1,
                            'icon' => 'element-Money',
                            'api_url' => '',
                            'router_path' => 'money',
                            'view_path' => 'member/money',
                            'methods' => '',
                            'sort' => 59,
                            'status' => 1,
                            'is_show' => 1,
                            'en_menu_name' => '',
                        ],
                    ],
            ],
            [
                'menu_name' => '财务管理',
                'menu_key' => 'finance',
                'menu_type' => 0,
                'icon' => 'element-Box',
                'api_url' => '',
                'router_path' => 'finance',
                'view_path' => '',
                'methods' => '',
                'sort' => 60,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '会员充值',
                        'menu_key' => 'recharge_list',
                        'menu_type' => 1,
                        'icon' => 'element-Help',
                        'api_url' => '',
                        'router_path' => 'recharge',
                        'view_path' => 'finance/recharge/list',
                        'methods' => '',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '充值详情',
                        'menu_key' => 'recharge_order_info',
                        'menu_type' => 1,
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'finance/detail',
                        'view_path' => 'finance/recharge/detail',
                        'methods' => '',
                        'sort' => 90,
                        'status' => 1,
                        'is_show' => 0,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '会员提现',
                        'menu_key' => 'withdrawal_list',
                        'menu_type' => 1,
                        'icon' => 'element-Postcard',
                        'api_url' => '',
                        'router_path' => 'withdrawal',
                        'view_path' => 'finance/withdrawal',
                        'methods' => '',
                        'sort' => 99,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ]
                ]
            ],

            [

                'menu_name' => '渠道管理',
                'menu_key' => 'channel',
                'menu_type' => 0,
                'icon' => 'element-DataBoard',
                'api_url' => '',
                'router_path' => 'channel',
                'view_path' => '',
                'methods' => '',
                'sort' => 50,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '微信公众号',
                        'menu_key' => 'channel_wechat',
                        'menu_type' => 0,
                        'icon' => 'iconfont-iconweixingongzhonghao1',
                        'api_url' => '',
                        'router_path' => 'wechat',
                        'view_path' => '',
                        'methods' => '',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [
                            [
                                'menu_name' => '公众号配置',
                                'menu_key' => 'wechat_config',
                                'menu_type' => 1,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => 'config',
                                'view_path' => 'channel/wechat/config',
                                'methods' => '',
                                'sort' => 100,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '自定义菜单',
                                'menu_key' => 'wechat_menu',
                                'menu_type' => 1,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => 'menu',
                                'view_path' => 'channel/wechat/menu',
                                'methods' => '',
                                'sort' => 90,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '模板消息',
                                'menu_key' => 'wechat_template_message',
                                'menu_type' => 1,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => 'message',
                                'view_path' => 'channel/wechat/template',
                                'methods' => '',
                                'sort' => 70,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ]
                        ]
                    ],
                    [
                        'menu_name' => '微信小程序',
                        'menu_key' => 'channel_weapp',
                        'menu_type' => 0,
                        'icon' => 'iconfont-iconxiaochengxushezhi',
                        'api_url' => '',
                        'router_path' => 'weapp',
                        'view_path' => '',
                        'methods' => '',
                        'sort' => 90,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [
                            [
                                'menu_name' => '小程序配置',
                                'menu_key' => 'weapp_config',
                                'menu_type' => 1,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => 'config',
                                'view_path' => 'channel/weapp/config',
                                'methods' => '',
                                'sort' => 100,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '订阅消息',
                                'menu_key' => 'weapp_template_message',
                                'menu_type' => 1,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => 'message',
                                'view_path' => 'channel/weapp/template',
                                'methods' => '',
                                'sort' => 90,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ]
                        ]
                    ]
                ]
            ],
            [
                'menu_name' => '权限管理',
                'menu_key' => 'auth',
                'menu_type' => 0,
                'icon' => 'element-Lock',
                'api_url' => '',
                'router_path' => 'auth',
                'view_path' => '',
                'methods' => '',
                'sort' => 40,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '菜单管理',
                        'menu_key' => 'menu_list',
                        'menu_type' => 1,
                        'icon' => 'element-Operation',
                        'api_url' => '',
                        'router_path' => 'menu',
                        'view_path' => '',
                        'methods' => '',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [
                            [
                                'menu_name' => '平台菜单',
                                'menu_key' => 'auth_menu',
                                'menu_type' => 1,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => 'admin',
                                'view_path' => 'auth/menu',
                                'methods' => '',
                                'sort' => 100,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                                'children' => [
                                    [
                                        'menu_name' => '新增',
                                        'menu_key' => 'auth_menu_add',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => '',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => '',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '编辑',
                                        'menu_key' => 'auth_menu_update',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => '',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => '',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '删除',
                                        'menu_key' => 'auth_menu_del',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => '',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => '',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '详情',
                                        'menu_key' => 'auth_menu_info',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => '',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => '',
                                        'sort' => 0,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                ],
                            ],
                            [
                                'menu_name' => '站点菜单',
                                'menu_key' => 'auth_site_menu',
                                'menu_type' => 1,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => 'site',
                                'view_path' => 'auth/site_menu',
                                'methods' => '',
                                'sort' => 90,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                                'children' => [
                                    [
                                        'menu_name' => '新增',
                                        'menu_key' => 'auth_site_menu_add',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => '',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => '',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '编辑',
                                        'menu_key' => 'auth_site_menu_update',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => '',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => '',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '删除',
                                        'menu_key' => 'auth_site_menu_del',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => '',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => '',
                                        'sort' => 1,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                    [
                                        'menu_name' => '详情',
                                        'menu_key' => 'auth_site_menu_info',
                                        'menu_type' => 2,
                                        'icon' => '',
                                        'api_url' => '',
                                        'router_path' => '',
                                        'view_path' => '',
                                        'methods' => '',
                                        'sort' => 0,
                                        'status' => 1,
                                        'is_show' => 1,
                                        'en_menu_name' => '',
                                    ],
                                ],
                            ]
                        ]
                    ],
                    [

                        'menu_name' => '管理员',
                        'menu_key' => 'auth_user',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconyonghu',
                        'api_url' => '',
                        'router_path' => 'user',
                        'view_path' => 'auth/user',
                        'methods' => '',
                        'sort' => 80,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [
                            [
                                'menu_name' => '新增',
                                'menu_key' => 'auth_user_add',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => '',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '编辑',
                                'menu_key' => 'auth_user_update',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => '',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '删除',
                                'menu_key' => 'auth_user_del',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => '',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '详情',
                                'menu_key' => 'auth_user_info',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => 'sys/user/<uid>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => 0,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '角色管理',
                        'menu_key' => 'auth_role',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconhuiyuanliebiao',
                        'api_url' => '',
                        'router_path' => 'role',
                        'view_path' => 'auth/role',
                        'methods' => '',
                        'sort' => 70,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [
                            [
                                'menu_name' => '新增',
                                'menu_key' => 'auth_role_add',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => '',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '编辑',
                                'menu_key' => 'auth_role_update',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => '',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '删除',
                                'menu_key' => 'auth_role_del',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => '',
                                'sort' => 1,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                        ]
                    ],
                    [
                        'menu_name' => '操作日志',
                        'menu_key' => 'auth_log',
                        'menu_type' => 1,
                        'icon' => 'element-Document',
                        'api_url' => '',
                        'router_path' => 'log',
                        'view_path' => 'auth/log',
                        'methods' => '',
                        'sort' => 60,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                ]
            ],
            [
                'menu_name' => '站点管理',
                'menu_key' => 'site',
                'menu_type' => 0,
                'icon' => 'element-Memo',
                'api_url' => '',
                'router_path' => 'site',
                'view_path' => '',
                'methods' => '',
                'sort' => 30,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '站点列表',
                        'menu_key' => 'site_list',
                        'menu_type' => 1,
                        'icon' => 'element-OfficeBuilding',
                        'api_url' => '',
                        'router_path' => 'list',
                        'view_path' => 'site/list',
                        'methods' => '',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '站点详情',
                        'menu_key' => 'site_info',
                        'menu_type' => 1,
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'info',
                        'view_path' => 'site/info',
                        'methods' => '',
                        'sort' => 90,
                        'status' => 1,
                        'is_show' => 0,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '站点套餐',
                        'menu_key' => 'site_group',
                        'menu_type' => 1,
                        'icon' => 'element-PriceTag',
                        'api_url' => '',
                        'router_path' => 'group',
                        'view_path' => 'site/group',
                        'methods' => '',
                        'sort' => 80,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '站点用户',
                        'menu_key' => 'site_user',
                        'menu_type' => 1,
                        'icon' => 'element-User',
                        'api_url' => '',
                        'router_path' => 'user',
                        'view_path' => 'site/user',
                        'methods' => '',
                        'sort' => 70,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ]
                ]
            ],
            [
                'menu_name' => '系统设置',
                'menu_key' => 'setting',
                'menu_type' => 0,
                'icon' => 'element-Setting',
                'api_url' => '',
                'router_path' => 'setting',
                'view_path' => '',
                'methods' => '',
                'sort' => 20,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '网站设置',
                        'menu_key' => 'setting_system',
                        'menu_type' => 1,
                        'icon' => 'element-Basketball',
                        'api_url' => '',
                        'router_path' => 'system',
                        'view_path' => 'setting/system',
                        'methods' => '',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '版权设置',
                        'menu_key' => 'setting_copyright',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconbanquan1',
                        'api_url' => '',
                        'router_path' => 'copyright',
                        'view_path' => 'setting/copyright',
                        'methods' => '',
                        'sort' => 90,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '协议管理',
                        'menu_key' => 'system_agreement',
                        'menu_type' => 1,
                        'icon' => 'element-Notebook',
                        'api_url' => '',
                        'router_path' => 'agreement',
                        'view_path' => 'setting/agreement',
                        'methods' => '',
                        'sort' => 80,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [

                        ]
                    ],
                    [
                        'menu_name' => '协议编辑',
                        'menu_key' => 'system_agreement_edit',
                        'menu_type' => 1,
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'agreement/edit',
                        'view_path' => 'setting/agreement_edit',
                        'methods' => '',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 0,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '注册登录',
                        'menu_key' => 'setting_login_register',
                        'menu_type' => 1,
                        'icon' => 'iconfont-icondenglu',
                        'api_url' => '',
                        'router_path' => 'login',
                        'view_path' => 'setting/login',
                        'methods' => '',
                        'sort' => 70,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '支付设置',
                        'menu_key' => 'setting_pay',
                        'menu_type' => 1,
                        'icon' => 'element-Wallet',
                        'api_url' => '',
                        'router_path' => 'pay',
                        'view_path' => 'setting/pay',
                        'methods' => '',
                        'sort' => 60,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [
                            [
                                'menu_name' => '微信支付',
                                'menu_key' => 'setting_wechatpay',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => 'wechatpay',
                                'view_path' => '',
                                'methods' => '',
                                'sort' => 0,
                                'status' => 1,
                                'is_show' => 0,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '支付宝支付',
                                'menu_key' => 'setting_alipay',
                                'menu_type' => 2,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => 'alipay',
                                'view_path' => '',
                                'methods' => '',
                                'sort' => 0,
                                'status' => 1,
                                'is_show' => 0,
                                'en_menu_name' => '',
                            ]
                        ]
                    ],
                    [
                        'menu_name' => '提现设置',
                        'menu_key' => 'withdrawal_config',
                        'menu_type' => 1,
                        'icon' => 'element-Postcard',
                        'api_url' => '',
                        'router_path' => 'withdrawal',
                        'view_path' => 'setting/withdrawal',
                        'methods' => '',
                        'sort' => 59,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '消息管理',
                        'menu_key' => 'setting_message',
                        'menu_type' => 1,
                        'icon' => 'element-ChatLineSquare',
                        'api_url' => '',
                        'router_path' => 'message',
                        'view_path' => '',
                        'methods' => '',
                        'sort' => 50,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                        'children' => [
                            [
                                'menu_name' => '消息模板',
                                'menu_key' => 'setting_message_template',
                                'menu_type' => 1,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => 'template',
                                'view_path' => 'setting/message',
                                'methods' => '',
                                'sort' => 10,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ],
                            [
                                'menu_name' => '发送记录',
                                'menu_key' => 'setting_message_records',
                                'menu_type' => 1,
                                'icon' => '',
                                'api_url' => '',
                                'router_path' => 'records',
                                'view_path' => 'setting/message_records',
                                'methods' => '',
                                'sort' => 9,
                                'status' => 1,
                                'is_show' => 1,
                                'en_menu_name' => '',
                            ]
                        ]
                    ],
                    [
                        'menu_name' => '短信设置',
                        'menu_key' => 'setting_sms',
                        'menu_type' => 1,
                        'icon' => 'element-Message',
                        'api_url' => '',
                        'router_path' => 'sms',
                        'view_path' => 'setting/sms',
                        'methods' => '',
                        'sort' => 40,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '存储设置',
                        'menu_key' => 'setting_storage',
                        'menu_type' => 1,
                        'icon' => 'element-FolderChecked',
                        'api_url' => '',
                        'router_path' => 'storage',
                        'view_path' => 'setting/storage',
                        'methods' => '',
                        'sort' => 30,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '定时任务',
                        'menu_key' => 'system_cron',
                        'menu_type' => 1,
                        'icon' => 'element-SetUp',
                        'api_url' => '',
                        'router_path' => 'cron',
                        'view_path' => 'setting/cron',
                        'methods' => '',
                        'sort' => 20,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ]
                ]
            ],
            [
                'menu_name' => '开发工具',
                'menu_key' => 'tool',
                'menu_type' => 0,
                'icon' => 'element-Edit',
                'api_url' => '',
                'router_path' => 'tools',
                'view_path' => '',
                'methods' => '',
                'sort' => 10,
                'status' => 1,
                'is_show' => 1,
                'en_menu_name' => '',
                'children' => [
                    [
                        'menu_name' => '代码生成',
                        'menu_key' => 'code',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconyuandaima',
                        'api_url' => '',
                        'router_path' => 'code',
                        'view_path' => 'tools/code/index',
                        'methods' => '',
                        'sort' => 100,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '应用市场',
                        'menu_key' => 'app_store',
                        'menu_type' => 1,
                        'icon' => 'iconfont-iconyingyongshichang',
                        'api_url' => '',
                        'router_path' => 'app_store',
                        'view_path' => 'tools/app/index',
                        'methods' => '',
                        'sort' => 90,
                        'status' => 1,
                        'is_show' => 1,
                        'en_menu_name' => '',
                    ],
                    [
                        'menu_name' => '数据表编辑',
                        'menu_key' => 'code_edit',
                        'menu_type' => 1,
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'code/edit',
                        'view_path' => 'tools/code/edit',
                        'methods' => '',
                        'sort' => 80,
                        'status' => 1,
                        'is_show' => 0,
                        'en_menu_name' => '',
                    ],
                ]
            ]
        ];